---
apiVersion: "stable.k8s.psg.io/v1"
kind: "Certificate"
metadata:
  labels:
    app: {{ template "__CHART__.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "__CHART__.fullname" . }}
spec:
  domain: {{ .Values.Certificate.Domain | quote }}
  email: {{ .Values.Certificate.Email | quote }}
  provider: {{ .Values.Certificate.Provider | quote }}
  secretName: "tls-{{ template "__CHART__.fullname" . }}"

