---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "fullname" . }}
spec:
  replicas: {{ default 2 .Values.replicas }}
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
      release: "{{ .Release.Name }}"
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: "RollingUpdate"
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        release: "{{ .Release.Name }}"
    spec:
      # volumes:
      #   - name: "webserver-etc-conf-d"
      # configMap:
      #   - name: "webserver-data"
      #     hostPath:
      #       path: /data/webserver/
      containers:
        - name: {{ template "name" }}
          # env:
          # - name: "FOO"
          #   value: "BAR"
          image: {{ .Values.image | quote }}
          # args:
          #   - "command"
          #   - "line"
          #   - "arguments"
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu | quote }}
              memory: {{ .Values.resources.limits.memory | quote }}
            requests:
              cpu: {{ .Values.resources.requests.cpu | quote }}
              memory: {{ .Values.resources.requests.memory | quote }}
          securityContext:
            privileged: {{ default "false" .Values.securityContext.privileged }}
            # capabilities:
              # add:
                # - "SETPCAP"
                # - "SYS_MODULE"
                # - "SYS_RAWIO"
                # - "SYS_PACCT"
                # - "SYS_ADMIN"
                # - "SYS_NICE"
                # - "SYS_RESOURCE"
                # - "SYS_TIME"
                # - "SYS_TTY_CONFIG"
                # - "MKNOD"
                # - "AUDIT_WRITE"
                # - "AUDIT_CONTROL"
                # - "MAC_OVERRIDE"
                # - "MAC_ADMIN"
                # - "NET_ADMIN"
                # - "SYSLOG"
                # - "CHOWN"
                # - "NET_RAW"
                # - "DAC_OVERRIDE"
                # - "FOWNER"
                # - "DAC_READ_SEARCH"
                # - "FSETID"
                # - "KILL"
                # - "SETGID"
                # - "SETUID"
                # - "LINUX_IMMUTABLE"
                # - "NET_BIND_SERVICE"
                # - "NET_BROADCAST"
                # - "IPC_LOCK"
                # - "IPC_OWNER"
                # - "SYS_CHROOT"
                # - "SYS_PTRACE"
                # - "SYS_BOOT"
                # - "LEASE"
                # - "SETFCAP"
                # - "WAKE_ALARM"
                # - "BLOCK_SUSPEND"
          ports:
            - containerPort: __CONTAINER_PORT__
              protocol: __CONTAINER_PORT_PROTOCOL__
              name: __CONTAINER_PORT_NAME__
          # volumeMounts:
          #   - name: "webserver-etc-conf-d"
          #     readOnly: true
          #     mountPath: "/etc/webserver/conf.d"
          #   - name: "webserver-data
          #     readOnly: false
          #     mountPath: "/data"
          livenessProbe:
            tcpSocket:
              port: __CONTAINER_PORT_NAME__
            initialDelaySeconds: 5
            timeoutSeconds: 1
          readinessProbe:
            tcpSocket:
              port: __CONTAINER_PORT_NAME__
            initialDelaySeconds: 5
            timeoutSeconds: 1
      restartPolicy: __RESTART_POLICY__
      securityContext: {}
