{{- if not .Values.Persistence.existingClaim }}
---
kind: "PersistentVolumeClaim"
apiVersion: "v1"
metadata:
  name: {{ template "__CHART__.fullname" . }}
  annotations:
  {{- if .Values.Persistence.StorageClass }}
    volume.beta.kubernetes.io/storage-class: {{ .Values.Persistence.StorageClass | quote }}
  {{- else }}
    volume.alpha.kubernetes.io/storage-class: "generic"
  {{- end }}
spec:
  accessModes:
    - {{ default "ReadWriteOnce" .Values.Persistence.AccessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.Persistence.Size | quote }}
{{- end }}
