---
apiVersion: "rbac.authorization.k8s.io/v1alpha1"
kind: "ClusterRole"
metadata:
  name: "__ROLE_NAME__"
  labels:
    app: {{ template "__CHART__.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
rules:
  - apiGroups:
      - ""
    resources:
      # - "nodes"
      # - "pods"
      # - "services"
      # - "resourcequotas"
      # - "replicationcontrollers"
      # - "limitranges"
    verbs:
      # - "list"
      # - "watch"
  - apiGroups:
      # - "extensions"
    resources:
      # - "daemonsets"
      # - "deployments"
      # - "replicasets"
    verbs:
      # - "list"
      # - "watch"
