---
kind: "Service"
apiVersion: "v1"
metadata:
  annotations:
    prometheus.io/scrape: "{{ .Values.Monitoring.Service.Scrape }}"
    {{ if eq .Values.Service.Type "LocaBalancer" -}}
    service.beta.kubernetes.io/external-traffic: "OnlyLocal"
    {{ end -}}
  labels:
    app: {{ template "__CHART__.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "__CHART__.fullname" . }}
spec:
  selector:
    app: {{ template "__CHART__.fullname" . }}
    release: "{{ .Release.Name }}"
  ports:
    - protocol: "__CONTAINER_PORT_PROTOCOL__"
      name: "__CONTAINER_PORT_NAME__"
      port: __CONTAINER_PORT__
  type: {{ default "ClusterIP" .Values.Service.Type }}
  {{ if eq .Values.Service.Type "LoadBalancer" -}}
  {{ if .Values.Service.LoadBalancer.PublicIp -}}
  loadBalancerIP: {{ .Values.Service.LoadBalancer.PublicIp }}
  {{ end -}}
  {{ end -}}
