---
apiVersion: "stable.k8s.psg.io/v1"
kind: "Certificate"
metadata:
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "fullname" . }}
spec:
  domain: {{ .Values.certificate.domain | quote }}
  email: {{ .Values.certificate.email | quote }}
  provider: {{ .Values.certificate.provider | quote }}
  secretName: "tls-{{ template "fullname" . }}"

